export const SET_DETAIL_ASSIGNMENT = 'SET_DETAIL_ASSIGNMENT';
export const GET_DETAIL_ASSIGNMENT = 'GET_DETAIL_ASSIGNMENT';
export const SET_FILE_SUBMIT = 'SET_FULL_SUBMIT';
export const SUBMIT_ASSIGNMENT = 'SUBMIT_ASSIGNMENT';
export const DELETE_ASSIGNMENT = 'DELETE_ASSIGNMENT';
