export const SET_COURSE_ASSIGNMENT = 'SET_COURSE_ASSIGNMENT';
export const SET_COURSE = 'SET_COURSE';
export const GET_COURSE_ASSIGNMENT = 'GET_COURSE_ASSIGNMENT';
export const DELETE_COURSE = 'DELETE_COURSE';
export const EDIT_COURSE = 'EDIT_COURSE';
